"""Export a Wireshark Lua dissector from DBC signal definitions."""
from typing import List


def signals_to_lua_dissector(signal_defs: List[dict]) -> str:
    """
    Generate a Wireshark post-dissector .lua file from signal dicts.

    The resulting script registers a protocol named "CANLAB_DBC" and
    decodes each message ID's signals from the CAN payload.

    Load in Wireshark: Edit → Preferences → Plugins → add path,
    or copy to ~/.config/wireshark/plugins/.
    """

    # Group signals by message ID
    messages: dict[int, dict] = {}
    for sig in signal_defs:
        try:
            mid = int(sig.get("message_id", "0"), 16)
        except (ValueError, TypeError):
            mid = 0
        if mid not in messages:
            messages[mid] = {
                "name":    sig.get("message_name", f"MSG_{mid:03X}"),
                "signals": [],
            }
        messages[mid]["signals"].append(sig)

    lines = []
    lines += [
        '-- Auto-generated by CANLAB',
        '-- Load with: Wireshark → Analyze → Run Lua Script',
        '',
        'local canlab_proto = Proto("CANLAB_DBC", "CANLAB DBC Dissector")',
        '',
        '-- Field definitions',
    ]

    # Declare protofields
    field_vars = []
    for mid, mdata in sorted(messages.items()):
        for sig in mdata["signals"]:
            sname   = sig.get("signal_name", "unknown")
            safe    = _lua_safe(sname)
            unit    = sig.get("unit", "")
            desc    = sig.get("description", sname)
            field_var = f"f_{mid:03X}_{safe}"
            field_vars.append(field_var)
            lines.append(
                f'local {field_var} = ProtoField.double("canlab_dbc.{mid:03X}.{safe}", '
                f'"{sname} ({unit})", nil, "{desc}")'
            )

    lines += [
        '',
        'canlab_proto.fields = {' + ', '.join(field_vars) + '}',
        '',
        'function canlab_proto.dissector(buffer, pinfo, tree)',
        '    local can_id_field = Field.new("can.id")',
        '    local can_data_field = Field.new("can.data")',
        '    if not can_id_field then return end',
        '    local can_id_fi = can_id_field()',
        '    if not can_id_fi then return end',
        '    local can_id = can_id_fi.value',
        '',
        '    -- Signal bit offsets are relative to the CAN *data* field, not the',
        '    -- full capture buffer. Extract the payload as its own tvb so the',
        '    -- offsets line up.',
        '    local data_buf = buffer',
        '    if can_data_field then',
        '        local can_data_fi = can_data_field()',
        '        if can_data_fi then data_buf = can_data_fi.range:tvb() end',
        '    end',
        '',
        '    local subtree = tree:add(canlab_proto, buffer(), "CANLAB: " .. string.format("0x%03X", can_id))',
        '',
    ]

    # Per-message decoding block
    for mid, mdata in sorted(messages.items()):
        mname = mdata["name"]
        lines.append(f'    if can_id == 0x{mid:03X} then  -- {mname}')
        lines.append(f'        subtree:append_text(" ({mname})")')
        for sig in mdata["signals"]:
            sname   = sig.get("signal_name", "unknown")
            safe    = _lua_safe(sname)
            start   = int(sig.get("start_bit", 0))
            length  = int(sig.get("length", 8))
            scale   = float(sig.get("scale", 1.0))
            offset  = float(sig.get("offset", 0.0))
            signed  = sig.get("value_type", "unsigned").lower() == "signed"
            bo      = sig.get("byte_order", "little")
            unit    = sig.get("unit", "")
            field_var = f"f_{mid:03X}_{safe}"

            lines.append(
                f'        -- {sname}: start={start} len={length} bo={bo}'
            )
            lines += [
                f'        local raw_{safe} = extract_bits(data_buf, {start}, {length}, "{bo}", {str(signed).lower()})',
                f'        local val_{safe} = raw_{safe} * {scale} + {offset}',
                f'        subtree:add({field_var}, val_{safe}):append_text(" {unit}")',
            ]
        lines.append('    end')
        lines.append('')

    lines += [
        'end',
        '',
        '-- Bit extraction helper',
        'function extract_bits(buf, start_bit, length, byte_order, is_signed)',
        '    local result = 0',
        '    if byte_order == "little" then',
        '        for i = 0, length - 1 do',
        '            local bit_pos = start_bit + i',
        '            local byte_i = math.floor(bit_pos / 8)',
        '            local bit_i  = bit_pos % 8',
        '            if byte_i < buf:len() then',
        '                local b = buf(byte_i, 1):uint()',
        '                if bit32.band(b, bit32.lshift(1, bit_i)) ~= 0 then',
        '                    result = result + bit32.lshift(1, i)',
        '                end',
        '            end',
        '        end',
        '    else',
        '        -- big endian (Motorola sawtooth) — matches cantools/DBC @0',
        '        local pos = start_bit',
        '        for i = 0, length - 1 do',
        '            local byte_i = math.floor(pos / 8)',
        '            local bit_i  = pos % 8',
        '            if byte_i < buf:len() then',
        '                local b = buf(byte_i, 1):uint()',
        '                local bit = bit32.band(bit32.rshift(b, bit_i), 1)',
        '                result = result * 2 + bit',
        '            end',
        '            if bit_i == 0 then',
        '                pos = pos + 15',
        '            else',
        '                pos = pos - 1',
        '            end',
        '        end',
        '    end',
        '    if is_signed and result >= bit32.lshift(1, length - 1) then',
        '        result = result - bit32.lshift(1, length)',
        '    end',
        '    return result',
        'end',
        '',
        '-- Register on CAN frames',
        'local can_table = DissectorTable.get("can.subdissector")',
        'if can_table then',
        '    can_table:add_for_decode_as(canlab_proto)',
        'else',
        '    register_postdissector(canlab_proto)',
        'end',
    ]

    return "\n".join(lines) + "\n"


def _lua_safe(name: str) -> str:
    """Make a signal name safe for use as a Lua identifier."""
    return "".join(c if c.isalnum() or c == "_" else "_" for c in name)
